import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const session = await getServerSession(authOptions);
  if (!session) {
    return NextResponse.json({ error: 'Unauthorised' }, { status: 401 });
  }

  const { id } = await params;

  // Allow BOTH landlord (via property ownership) and tenant (via tenancy) to download.
  // Previously this only checked the landlord chain, so tenants got a 404.
  const agreement = await prisma.agreement.findFirst({
    where: {
      id,
      tenancy: {
        OR: [
          { property: { landlordId: session.user.id } }, // landlord access
          { tenantId: session.user.id }, // tenant access
        ],
      },
    },
    include: {
      tenancy: {
        include: {
          property: { select: { address: true, city: true, state: true } },
          tenant: { select: { name: true } },
        },
      },
    },
  });

  if (!agreement) {
    return NextResponse.json(
      { error: 'Agreement not found or access denied' },
      { status: 404 },
    );
  }

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <style>
    body { font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.8; color: #1a1a1a; max-width: 800px; margin: 0 auto; padding: 60px 80px; }
    h1 { text-align: center; font-size: 16pt; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 8px; }
    .subtitle { text-align: center; font-size: 10pt; color: #555; margin-bottom: 40px; }
    .divider { border: none; border-top: 2px solid #1a1a1a; margin: 24px 0; }
    pre { white-space: pre-wrap; font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.8; }
    .footer { margin-top: 60px; font-size: 9pt; color: #888; text-align: center; }
  </style>
</head>
<body>
  <h1>Residential Tenancy Agreement</h1>
  <p class="subtitle">
    ${agreement.tenancy.property.address}, ${agreement.tenancy.property.city}, ${agreement.tenancy.property.state}<br/>
    Tenant: ${agreement.tenancy.tenant.name}
  </p>
  <hr class="divider" />
  <pre>${agreement.rawContent}</pre>
  <hr class="divider" />
  <p class="footer">
    Generated by RentalEase Malaysia &mdash; AI-Assisted Digital Tenancy Agreement Platform<br/>
    Document ID: ${agreement.id} &mdash; Status: ${agreement.status}
  </p>
</body>
</html>`;

  const fileName = `tenancy-agreement-${agreement.tenancy.tenant.name.replace(/\s+/g, '-')}.html`;

  return new NextResponse(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `attachment; filename="${fileName}"`,
    },
  });
}
