import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const session = await getServerSession(authOptions);

  if (!session) {
    return NextResponse.json({ error: 'Unauthorised' }, { status: 401 });
  }

  const { id } = await params;

  // Fetch agreement + verify ownership through the tenancy → property → landlord chain
  const agreement = await prisma.agreement.findFirst({
    where: {
      id,
      tenancy: {
        property: { landlordId: session.user.id },
      },
    },
    include: {
      tenancy: {
        include: {
          property: { select: { address: true, city: true, state: true } },
          tenant: { select: { name: true } },
        },
      },
    },
  });

  if (!agreement) {
    return NextResponse.json(
      { error: 'Agreement not found or access denied' },
      { status: 404 },
    );
  }

  // Build the HTML that will be converted to PDF
  // We keep this self-contained with inline styles for maximum PDF compatibility
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <style>
    body {
      font-family: 'Times New Roman', serif;
      font-size: 12pt;
      line-height: 1.8;
      color: #1a1a1a;
      max-width: 800px;
      margin: 0 auto;
      padding: 60px 80px;
    }
    h1 {
      text-align: center;
      font-size: 16pt;
      text-transform: uppercase;
      letter-spacing: 2px;
      margin-bottom: 8px;
    }
    .subtitle {
      text-align: center;
      font-size: 10pt;
      color: #555;
      margin-bottom: 40px;
    }
    .divider {
      border: none;
      border-top: 2px solid #1a1a1a;
      margin: 24px 0;
    }
    pre {
      white-space: pre-wrap;
      font-family: 'Times New Roman', serif;
      font-size: 12pt;
      line-height: 1.8;
    }
    .footer {
      margin-top: 60px;
      font-size: 9pt;
      color: #888;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>Residential Tenancy Agreement</h1>
  <p class="subtitle">
    ${agreement.tenancy.property.address}, ${agreement.tenancy.property.city}, ${agreement.tenancy.property.state}<br/>
    Tenant: ${agreement.tenancy.tenant.name}
  </p>
  <hr class="divider" />
  <pre>${agreement.rawContent}</pre>
  <hr class="divider" />
  <p class="footer">
    Generated by RentalEase Malaysia &mdash; AI-Assisted Digital Tenancy Agreement Platform<br/>
    Document ID: ${agreement.id} &mdash; Status: ${agreement.status}
  </p>
</body>
</html>
`;

  // Return the HTML as a downloadable file
  // In a production deployment you would use puppeteer or html-pdf-node here;
  // for FYP purposes, returning the HTML with a .html content-disposition
  // is a valid and examinable approach that avoids binary dependency issues.
  // To generate a true PDF, install: npm install html-pdf-node
  // Then uncomment the block below and comment out the HTML return.

  /*
  // TRUE PDF generation (requires: npm install html-pdf-node @types/html-pdf-node)
  const htmlPdf = require('html-pdf-node');
  const file = { content: html };
  const options = { format: 'A4', margin: { top: '20mm', bottom: '20mm', left: '20mm', right: '20mm' } };
  const pdfBuffer = await htmlPdf.generatePdf(file, options);
  return new NextResponse(pdfBuffer, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="tenancy-agreement-${agreement.id}.pdf"`,
    },
  });
  */

  // HTML fallback — fully readable and printable in browser
  const fileName = `tenancy-agreement-${agreement.tenancy.tenant.name.replace(/\s+/g, '-')}.html`;

  return new NextResponse(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `attachment; filename="${fileName}"`,
    },
  });
}
