import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const session = await getServerSession(authOptions);
  if (!session)
    return NextResponse.json({ error: 'Unauthorised' }, { status: 401 });

  const { id } = await params;

  // Both landlord and tenant can download — OR covers both auth paths
  const agreement = await prisma.agreement.findFirst({
    where: {
      id,
      tenancy: {
        OR: [
          { room: { property: { landlordId: session.user.id } } },
          { tenantId: session.user.id },
        ],
      },
    },
    include: {
      tenancy: {
        include: {
          room: {
            include: {
              property: { select: { address: true, city: true, state: true } },
            },
          },
          tenant: { select: { name: true } },
        },
      },
    },
  });

  if (!agreement)
    return NextResponse.json(
      { error: 'Agreement not found or access denied' },
      { status: 404 },
    );

  const { address, city, state } = agreement.tenancy.room.property;

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Tenancy Agreement — ${agreement.tenancy.tenant.name}</title>
  <style>
    body { font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.8; color: #1a1a1a; max-width: 800px; margin: 0 auto; padding: 60px 80px; }
    h1 { text-align: center; font-size: 16pt; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 8px; }
    .subtitle { text-align: center; font-size: 10pt; color: #555; margin-bottom: 40px; }
    .divider { border: none; border-top: 2px solid #1a1a1a; margin: 24px 0; }
    pre { white-space: pre-wrap; font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.8; }
    .footer { margin-top: 60px; font-size: 9pt; color: #888; text-align: center; border-top: 1px solid #ddd; padding-top: 16px; }
  </style>
</head>
<body>
  <h1>Residential Tenancy Agreement</h1>
  <p class="subtitle">
    ${address}, ${city}, ${state}<br/>
    Room: ${agreement.tenancy.room.label}<br/>
    Tenant: ${agreement.tenancy.tenant.name}
  </p>
  <hr class="divider" />
  <pre>${agreement.rawContent}</pre>
  <hr class="divider" />
  <p class="footer">
    Generated by RentalEase Malaysia<br/>
    Document ID: ${agreement.id} — Status: ${agreement.status}
  </p>
</body>
</html>`;

  const fileName = `tenancy-agreement-${agreement.tenancy.tenant.name.replace(/\s+/g, '-')}.html`;

  return new NextResponse(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `attachment; filename="${fileName}"`,
    },
  });
}
